from __future__ import annotations

import hashlib
import secrets

from ecdsa import BadSignatureError, SECP256k1, SigningKey, util


CURVE = SECP256k1
CURVE_ORDER = SECP256k1.order


def sha256_digest(message: bytes) -> bytes:
    """Return the SHA-256 digest of a message."""
    return hashlib.sha256(message).digest()


def verify_signature(
    verifying_key,
    message: bytes,
    signature_der: bytes,
) -> bool:
    """Return True only when the DER signature is valid for the message."""
    try:
        return verifying_key.verify(
            signature_der,
            message,
            hashfunc=hashlib.sha256,
            sigdecode=util.sigdecode_der,
        )
    except BadSignatureError:
        return False


def inverse_mod(value: int, modulus: int) -> int:
    """Compute a modular inverse."""
    return pow(value % modulus, -1, modulus)


def sign_digest_with_fixed_nonce(
    signing_key: SigningKey,
    digest: bytes,
    nonce_k: int,
) -> tuple[int, int]:
    """
    DELIBERATELY UNSAFE.

    This function signs using an explicitly supplied nonce k.
    It exists only to demonstrate the danger of nonce reuse with a
    fresh test key created during this script execution.

    Never use a fixed or repeated nonce in real ECDSA signing.
    """
    signature_raw = signing_key.sign_digest(
        digest,
        sigencode=util.sigencode_string,
        k=nonce_k,
    )

    r, s = util.sigdecode_string(signature_raw, CURVE_ORDER)
    return r, s


def recover_nonce_from_reused_nonce_signatures(
    z1: int,
    z2: int,
    s1: int,
    s2: int,
) -> int:
    """
    When two ECDSA signatures reuse the same nonce k:

    k = (z1 - z2) / (s1 - s2) mod n
    """
    numerator = (z1 - z2) % CURVE_ORDER
    denominator_inverse = inverse_mod(s1 - s2, CURVE_ORDER)

    return (numerator * denominator_inverse) % CURVE_ORDER


def recover_private_key(
    z1: int,
    r: int,
    s1: int,
    recovered_nonce: int,
) -> int:
    """
    After recovering k:

    private_key = (s1*k - z1) / r mod n
    """
    numerator = (s1 * recovered_nonce - z1) % CURVE_ORDER
    r_inverse = inverse_mod(r, CURVE_ORDER)

    return (numerator * r_inverse) % CURVE_ORDER


def print_section(title: str) -> None:
    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)


def main() -> None:
    # ------------------------------------------------------------
    # Exercise 3.1 — Sign and verify a transaction
    # ------------------------------------------------------------
    print_section("Exercise 3.1 — ECDSA Transaction Signing and Verification")

    alice_private_key = SigningKey.generate(curve=CURVE)
    alice_public_key = alice_private_key.get_verifying_key()

    bob_private_key = SigningKey.generate(curve=CURVE)
    bob_public_key = bob_private_key.get_verifying_key()

    message = (
        b"Alice sends 1 BTC to Bob | nonce: 12345 | timestamp: 2026-01-01"
    )

    altered_message = (
        b"Alice sends 2 BTC to Bob | nonce: 12345 | timestamp: 2026-01-01"
    )

    # Normal signing uses deterministic signing.
    # This avoids depending on an external random nonce for the normal case.
    signature_der = alice_private_key.sign_deterministic(
        message,
        hashfunc=hashlib.sha256,
        sigencode=util.sigencode_der,
    )

    r, s = util.sigdecode_der(signature_der, CURVE_ORDER)

    valid_original = verify_signature(
        alice_public_key,
        message,
        signature_der,
    )

    valid_altered = verify_signature(
        alice_public_key,
        altered_message,
        signature_der,
    )

    print("Alice public key:", alice_public_key.to_string().hex())
    print("Bob public key:  ", bob_public_key.to_string().hex())

    print("\nOriginal message:")
    print(message.decode("utf-8"))

    print("\nDER-encoded signature:")
    print(signature_der.hex())

    print("\nSignature components:")
    print("r =", r)
    print("s =", s)

    print("\nVerification using Alice's public key:")
    print("Original transaction valid:", valid_original)
    print("Altered transaction valid: ", valid_altered)

    assert valid_original is True
    assert valid_altered is False

    print("\nSignature integrity checks: PASSED")

    # ------------------------------------------------------------
    # Exercise 3.2 — Controlled nonce reuse demonstration
    # ------------------------------------------------------------
    print_section("Exercise 3.2 — Controlled ECDSA Nonce Reuse Demonstration")

    print(
        "WARNING: This section deliberately reuses one nonce only with a "
        "new temporary test key generated by this script."
    )

    message_1 = b"Alice sends 1 BTC to Bob | transaction=1"
    message_2 = b"Alice sends 2 BTC to Bob | transaction=2"

    digest_1 = sha256_digest(message_1)
    digest_2 = sha256_digest(message_2)

    z1 = int.from_bytes(digest_1, byteorder="big")
    z2 = int.from_bytes(digest_2, byteorder="big")

    original_private_scalar = int.from_bytes(
        alice_private_key.to_string(),
        byteorder="big",
    )

    # Generate one random nonce and intentionally reuse it.
    # This is the vulnerability demonstration.
    reused_nonce_k = secrets.randbelow(CURVE_ORDER - 1) + 1

    r1, s1 = sign_digest_with_fixed_nonce(
        alice_private_key,
        digest_1,
        reused_nonce_k,
    )

    r2, s2 = sign_digest_with_fixed_nonce(
        alice_private_key,
        digest_2,
        reused_nonce_k,
    )

    assert r1 == r2, "Same nonce should produce the same r component."
    assert s1 != s2, "Different messages should normally produce different s values."

    recovered_nonce_k = recover_nonce_from_reused_nonce_signatures(
        z1,
        z2,
        s1,
        s2,
    )

    recovered_private_scalar = recover_private_key(
        z1,
        r1,
        s1,
        recovered_nonce_k,
    )

    recovered_private_key = SigningKey.from_secret_exponent(
        recovered_private_scalar,
        curve=CURVE,
    )

    same_private_key = recovered_private_scalar == original_private_scalar
    same_public_key = (
        recovered_private_key.get_verifying_key().to_string()
        == alice_public_key.to_string()
    )
    same_nonce = recovered_nonce_k == reused_nonce_k

    print("Message 1:", message_1.decode("utf-8"))
    print("Message 2:", message_2.decode("utf-8"))

    print("\nSignature 1:")
    print("r1 =", r1)
    print("s1 =", s1)

    print("\nSignature 2:")
    print("r2 =", r2)
    print("s2 =", s2)

    print("\nNonce reuse indicators:")
    print("r1 equals r2:", r1 == r2)
    print("s1 differs from s2:", s1 != s2)

    print("\nRecovery checks:")
    print("Recovered nonce matches original nonce:", same_nonce)
    print("Recovered private key matches original:", same_private_key)
    print("Recovered public key matches Alice public key:", same_public_key)

    assert same_nonce is True
    assert same_private_key is True
    assert same_public_key is True

    print("\nNonce reuse vulnerability demonstration: PASSED")

    # ------------------------------------------------------------
    # Exercise 3 — short conceptual summary
    # ------------------------------------------------------------
    print_section("Concept Summary")

    print(
        "Non-repudiation: Alice cannot credibly deny authorising the "
        "transaction when a valid signature verifies against her public key."
    )
    print(
        "Private-key protection: only the signature is shared; the private key "
        "does not travel through the network."
    )
    print(
        "Nonce rule: ECDSA nonce k must be unique for every signature made "
        "with the same private key."
    )
    print(
        "Mitigation: use a cryptographically secure nonce source or deterministic "
        "nonce generation such as RFC 6979."
    )


if __name__ == "__main__":
    main()
